apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bandicoot-replicaset
  labels:
    app: replica-bandicoot
spec:
  template:
    metadata:
      name: bandicoot-pod
      labels:
        app: bandicoot-replicaset
    spec:
      containers:
      - name: bandicoot-kuard
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: bandicoot-replicaset
    
