apiVersion: v1
kind: Service
metadata:
  name: bandicoot-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30037
    port: 9091
    targetPort: 8080
  selector:
    app: bandicoot-replicaset