apiVersion: v1
kind: Pod
metadata:
  name: bandicoot-pod
  labels:
    app: bandicoot
spec:
  containers:
  - name: bandicoot-kuard
    image: gcr.io/kuar-demo/kuard-amd64:green
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
