apiVersion: v1
kind: Service
metadata:
  name: alpaca-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30036
    port: 9090
    targetPort: 8080
  selector:
    app: alpaca-replicaset