apiVersion: v1
kind: Pod
metadata:
  name: mykuard
  labels:
    name: kuard
    app: blue
    env: test
spec:
  volumes:
    - name: kuard-data
      persistentVolumeClaim:
        claimName: pvc-local
  containers:
  - name: kuard-blue
    image: gcr.io/kuar-demo/kuard-amd64:blue
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      - name: kuard-data
        mountPath: /test
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
    readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3