apiVersion: v1
kind: Pod
metadata:
  name: mykuard-chapter5
  labels:
    name: mykuard-chapter5
spec:
  volumes:
    - name:  "data-kuard"
      hostPath:
        path:  "/data"
        type: Directory
  containers:
  - name: kuard-container
    image: kherguner/kuard:latest
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      - name:  "data-kuard"
        mountPath: "/data"
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
    readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3