apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: star-wars-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: star-wars-replicaset
  template:
    metadata:
      name: star-wars-replicaset
      labels:
        app: star-wars-replicaset
        env: test
    spec:
      containers:
        - name: star-wars-replicaset
          image: kherguner/k8s_up_running:npm
          ports:
          - containerPort: 3000
          resources:
              requests:
                cpu: "0.1"
                memory: "128Mi"
              limits:
                cpu: "0.3"
                memory: "256Mi"